prefix = "."
dataset = "chinese_reviews_pos"
corpus = "line.toml"
index = "chinese_reviews_pos-idx"
stop-words = "lemur-stopwords.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
